name: vitessce-data
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.6
  - scikit-learn==0.20.3
  - pandas==0.24.1
  - flake8==3.6.0
  - pip
  - pip:
    - loompy==2.0.16
    - numcodecs==0.6.3 # 0.6.4 not working on MacOS: https://github.com/napari/napari/issues/665
    - zarr==2.3.2
    - dask==2.11.0
    - toolz==0.9.0
    - fsspec==0.3.3
    - tifffile==2020.2.16
    - iiif==1.0.6
    - apeer-ometiff-library==1.3.1
    - pyimzml==1.3.0
    - scikit-image==0.16.1